name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'
          cache-dependency-path: './capstone_project/hello-world/'

      - name: Install dependencies
        run: npm install
        working-directory: ./capstone_project/hello-world/

      - name: Run tests
        run: npm test
        working-directory: ./capstone_project/hello-world/


      - name: Build Docker image
        if: ${{ success() }}
        run: docker build -t hello-world ./capstone_project/hello-world/
